; Auto-generated. Do not edit!


(cl:in-package api-msg)


;//! \htmlinclude moveResult.msg.html

(cl:defclass <moveResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass moveResult (<moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name api-msg:<moveResult> is deprecated: use api-msg:moveResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader api-msg:result-val is deprecated.  Use api-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveResult>) ostream)
  "Serializes a message object of type '<moveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveResult>) istream)
  "Deserializes a message object of type '<moveResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveResult>)))
  "Returns string type for a message object of type '<moveResult>"
  "api/moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveResult)))
  "Returns string type for a message object of type 'moveResult"
  "api/moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveResult>)))
  "Returns md5sum for a message object of type '<moveResult>"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveResult)))
  "Returns md5sum for a message object of type 'moveResult"
  "13d5d28ceaaadbc975dd072a2e10b88a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveResult>)))
  "Returns full string definition for message of type '<moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveResult)))
  "Returns full string definition for message of type 'moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%uint32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveResult
    (cl:cons ':result (result msg))
))
