// Generated by gencpp from file api/moveGoal.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_MOVEGOAL_H
#define API_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api
{
template <class ContainerAllocator>
struct moveGoal_
{
  typedef moveGoal_<ContainerAllocator> Type;

  moveGoal_()
    : request()  {
    }
  moveGoal_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::api::moveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api::moveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveGoal_

typedef ::api::moveGoal_<std::allocator<void> > moveGoal;

typedef boost::shared_ptr< ::api::moveGoal > moveGoalPtr;
typedef boost::shared_ptr< ::api::moveGoal const> moveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api::moveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api::moveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::api::moveGoal_<ContainerAllocator1> & lhs, const ::api::moveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::api::moveGoal_<ContainerAllocator1> & lhs, const ::api::moveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::api::moveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::moveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::moveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::moveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::moveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::moveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "455b9c0e4ae3e33a8ca1b91a4de0c200";
  }

  static const char* value(const ::api::moveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x455b9c0e4ae3e33aULL;
  static const uint64_t static_value2 = 0x8ca1b91a4de0c200ULL;
};

template<class ContainerAllocator>
struct DataType< ::api::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api/moveGoal";
  }

  static const char* value(const ::api::moveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"string[] request\n"
;
  }

  static const char* value(const ::api::moveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api::moveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api::moveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api::moveGoal_<ContainerAllocator>& v)
  {
    s << indent << "request[]" << std::endl;
    for (size_t i = 0; i < v.request.size(); ++i)
    {
      s << indent << "  request[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MESSAGE_MOVEGOAL_H
