// Generated by gencpp from file api/MoveFeedback.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_MOVEFEEDBACK_H
#define API_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api
{
template <class ContainerAllocator>
struct MoveFeedback_
{
  typedef MoveFeedback_<ContainerAllocator> Type;

  MoveFeedback_()
    : progress(0)  {
    }
  MoveFeedback_(const ContainerAllocator& _alloc)
    : progress(0)  {
  (void)_alloc;
    }



   typedef uint8_t _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::api::MoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api::MoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveFeedback_

typedef ::api::MoveFeedback_<std::allocator<void> > MoveFeedback;

typedef boost::shared_ptr< ::api::MoveFeedback > MoveFeedbackPtr;
typedef boost::shared_ptr< ::api::MoveFeedback const> MoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api::MoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api::MoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::api::MoveFeedback_<ContainerAllocator1> & lhs, const ::api::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::api::MoveFeedback_<ContainerAllocator1> & lhs, const ::api::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace api

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::api::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::MoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::MoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0ccee79f15d1d61b42a87d5f604edbc";
  }

  static const char* value(const ::api::MoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0ccee79f15d1d61ULL;
  static const uint64_t static_value2 = 0xb42a87d5f604edbcULL;
};

template<class ContainerAllocator>
struct DataType< ::api::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api/MoveFeedback";
  }

  static const char* value(const ::api::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"uint8 progress\n"
"\n"
;
  }

  static const char* value(const ::api::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api::MoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api::MoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api::MoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MESSAGE_MOVEFEEDBACK_H
